In [1]:
# Import Splinter, BeautifulSoup, Regular Expression, and Time
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
import time
import pandas as pd

In [2]:

top_250_imdb = pd.read_csv("../Output/top_250_imdb.csv")
top_250_imdb.head(5)

   IMDb Rank               Movie Title Year Released  IMDb Rating
0          1  The Shawshank Redemption          1994          9.2
1          2             The Godfather          1972          9.1
2          3    The Godfather: Part II          1974          9.0
3          4           The Dark Knight          2008          9.0
4          5              12 Angry Men          1957          8.9

# Scaping Google

In [3]:
# Path to chromedriver
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [4]:
url = "https://www.google.com/search?q="
#browser.visit(url)

In [6]:
movie_list = top_250_imdb["Movie Title"]

base_url = 'https://www.google.com/search?q='

streaming = []
title = []
price = []

for movie in movie_list:
    query_url = (f'{base_url}{movie}')

    browser.visit(query_url)

    time.sleep(3)

    soup = bs(browser.html, 'lxml')


    results1 = soup.find_all('div', class_ = 'ellip bclEt')

    for result in results1:
     #   try:
            streaming.append(result.text)
            title.append(movie.capitalize())
      #  except:
       #     Streaming.append('None')
       #     Title.append('None')
            
    results2 = soup.find_all('div', class_ = 'ellip rsj3fb')

    for result in results2:
     #   try:
            price.append(result.text)
      #  except:
      #      price.append('None')
    if len(streaming) & len(title) != len(price):
        streaming.pop()
        title.pop()
            
    print(f'{movie}:{len(title)}, {len(streaming)}, {len(price)}')

The Shawshank Redemption:8, 8, 8
The Godfather:8, 8, 8
The Godfather: Part II:12, 12, 12
The Dark Knight:17, 17, 17
12 Angry Men:22, 22, 22
Schindler's List:28, 28, 28
The Lord of the Rings: The Return of the King:34, 34, 34
Pulp Fiction:42, 42, 42
The Good, the Bad and the Ugly:48, 48, 48
The Lord of the Rings: The Fellowship of the Ring:54, 54, 54
Fight Club:61, 61, 61
Forrest Gump:69, 69, 69
Inception:74, 74, 74
Star Wars: Episode V - The Empire Strikes Back:80, 80, 80
The Lord of the Rings: The Two Towers:85, 85, 85
The Matrix:90, 90, 90
Goodfellas:95, 95, 95
One Flew Over the Cuckoo's Nest:100, 100, 100
Seven Samurai:106, 106, 106
Se7en:111, 111, 111
Life Is Beautiful:119, 119, 119
City of God:124, 124, 124
The Silence of the Lambs:134, 134, 134
It's a Wonderful Life:139, 139, 139
Star Wars: Episode IV - A New Hope:145, 145, 145
Saving Private Ryan:155, 155, 155
Spirited Away:160, 160, 160
The Green Mile:166, 166, 166
Parasite:171, 171, 171
Interstellar:178, 178, 178
Hamilton:179, 179, 179
Léon: The Professional:187, 187, 187
The Usual Suspects:190, 190, 190
Harakiri:192, 192, 192
The Lion King:197, 197, 197
Back to the Future:202, 202, 202
The Pianist:207, 207, 207
Terminator 2: Judgment Day:216, 216, 216
American History X:220, 220, 220
Modern Times:222, 222, 222
Psycho:227, 227, 227
Gladiator:236, 236, 236
City Lights:243, 243, 243
The Departed:249, 249, 249
The Intouchables:252, 252, 252
Whiplash:257, 257, 257
The Prestige:262, 262, 262
Grave of the Fireflies:265, 265, 265
Once Upon a Time in the West:272, 272, 272
Casablanca:278, 278, 278
Cinema Paradiso:283, 283, 283
Rear Window:288, 288, 288
Alien:297, 297, 297
Apocalypse Now:304, 304, 304
Memento:310, 310, 310
Raiders of the Lost Ark:316, 316, 316
The Great Dictator:320, 320, 320
Joker:327, 327, 327
Django Unchained:333, 333, 333
The Lives of Others:338, 338, 338
Paths of Glory:343, 343, 343
The Shining:350, 350, 350
WALL·E:355, 355, 355
Avengers: Infinity War:360, 360, 360
Sunset Blvd:366, 366, 366
Princess Mononoke:371, 371, 371
Witness for the Prosecution:376, 376, 376
Spider-Man: Into the Spider-Verse:380, 380, 380
Dr:380, 380, 380
Oldboy:382, 382, 382
The Dark Knight Rises:387, 387, 387
Once Upon a Time in America:391, 391, 391
Avengers: Endgame:396, 396, 396
Aliens:405, 405, 405
Your Name:408, 408, 408
Coco:413, 413, 413
American Beauty:419, 419, 419
Braveheart:428, 428, 428
3 Idiots:431, 431, 431
Das Boot:435, 435, 435
Toy Story:435, 435, 435
High and Low:437, 437, 437
Amadeus:441, 441, 441
Taare Zameen Par:443, 443, 443
Star Wars: Episode VI - Return of the Jedi:449, 449, 449
Inglourious Basterds:457, 457, 457
Reservoir Dogs:462, 462, 462
Good Will Hunting:471, 471, 471
Capharnaüm:478, 478, 478
2001: A Space Odyssey:484, 484, 484
Requiem for a Dream:491, 491, 491
Vertigo:491, 491, 491
M:491, 491, 491
Dangal:492, 492, 492
1917:496, 496, 496
Eternal Sunshine of the Spotless Mind:502, 502, 502
The Hunt:505, 505, 505
Citizen Kane:511, 511, 511
Full Metal Jacket:516, 516, 516
Bicycle Thieves:522, 522, 522
The Kid:527, 527, 527
A Clockwork Orange:536, 536, 536
North by Northwest:542, 542, 542
Snatch:550, 550, 550
Singin' in the Rain:556, 556, 556
Scarface:564, 564, 564
Taxi Driver:570, 570, 570
Amélie:575, 575, 575
Lawrence of Arabia:579, 579, 579
Ikiru:585, 585, 585
Toy Story 3:591, 591, 591
The Sting:596, 596, 596
Metropolis:599, 599, 599
A Separation:604, 604, 604
For a Few Dollars More:609, 609, 609
Incendies:614, 614, 614
The Apartment:619, 619, 619
Double Indemnity:624, 624, 624
To Kill a Mockingbird:624, 624, 624
Come and See:625, 625, 625
Indiana Jones and the Last Crusade:631, 631, 631
Up:637, 637, 637
L:637, 637, 637
Heat:642, 642, 642
Monty Python and the Holy Grail:647, 647, 647
Die Hard:656, 656, 656
Rashômon:659, 659, 659
Anand:660, 660, 660
Yojimbo:663, 663, 663
Batman Begins:669, 669, 669
Green Book:677, 677, 677
Downfall:679, 679, 679
Children of Heaven:683, 683, 683
Unforgiven:689, 689, 689
Some Like It Hot:696, 696, 696
Ran:701, 701, 701
Howl's Moving Castle:706, 706, 706
A Beautiful Mind:714, 714, 714
The Great Escape:720, 720, 720
All About Eve:725, 725, 725
Casino:725, 725, 725
Pan's Labyrinth:731, 731, 731
The Wolf of Wall Street:738, 738, 738
The Secret in Their Eyes:744, 744, 744
Lock, Stock and Two Smoking Barrels:749, 749, 749
My Neighbor Totoro:754, 754, 754
Raging Bull:760, 760, 760
There Will Be Blood:766, 766, 766
Judgment at Nuremberg:766, 766, 766
The Treasure of the Sierra Madre:772, 772, 772
Babam ve Oglum:772, 772, 772
Three Billboards Outside Ebbing, Missouri:776, 776, 776
Dial M for Murder:782, 782, 782
The Gold Rush:782, 782, 782
Chinatown:790, 790, 790
V for Vendetta:796, 796, 796
No Country for Old Men:804, 804, 804
Shutter Island:810, 810, 810
The Seventh Seal:816, 816, 816
Inside Out:822, 822, 822
Warrior:829, 829, 829
The Elephant Man:835, 835, 835
Trainspotting:837, 837, 837
The Sixth Sense:846, 846, 846
The Thing:854, 854, 854
Jurassic Park:864, 864, 864
Gone with the Wind:870, 870, 870
Wild Strawberries:873, 873, 873
Blade Runner:879, 879, 879
Finding Nemo:885, 885, 885
The Truman Show:892, 892, 892
Room:899, 899, 899
The Bridge on the River Kwai:904, 904, 904
Stalker:909, 909, 909
Kill Bill: Vol:918, 918, 918
Fargo:924, 924, 924
Tokyo Story:930, 930, 930
The Third Man:935, 935, 935
On the Waterfront:940, 940, 940
Gran Torino:946, 946, 946
Memories of Murder:947, 947, 947
The Deer Hunter:952, 952, 952
Wild Tales:957, 957, 957
Klaus:958, 958, 958
Andhadhun:962, 962, 962
In the Name of the Father:967, 967, 967
Mary and Max:972, 972, 972
Gone Girl:979, 979, 979
Hacksaw Ridge:984, 984, 984
The Big Lebowski:990, 990, 990
The Grand Budapest Hotel:995, 995, 995
The Bandit:1000, 1000, 1000
Before Sunrise:1008, 1008, 1008
Catch Me If You Can:1013, 1013, 1013
To Be or Not to Be:1013, 1013, 1013
Persona:1013, 1013, 1013
Ford v Ferrari:1017, 1017, 1017
The General:1017, 1017, 1017
How to Train Your Dragon:1022, 1022, 1022
Prisoners:1027, 1027, 1027
Sherlock Jr:1031, 1031, 1031
Mr:1031, 1031, 1031
12 Years a Slave:1036, 1036, 1036
Barry Lyndon:1041, 1041, 1041
Mad Max: Fury Road:1046, 1046, 1046
Network:1052, 1052, 1052
Stand by Me:1057, 1057, 1057
Million Dollar Baby:1063, 1063, 1063
Cool Hand Luke:1069, 1069, 1069
Ben-Hur:1074, 1074, 1074
Hachi: A Dog's Tale:1082, 1082, 1082
Into the Wild:1090, 1090, 1090
The Wages of Fear:1093, 1093, 1093
Dead Poets Society:1098, 1098, 1098
Platoon:1103, 1103, 1103
Harry Potter and the Deathly Hallows: Part 2:1112, 1112, 1112
Monty Python's Life of Brian:1117, 1117, 1117
Logan:1122, 1122, 1122
Rush:1122, 1122, 1122
Rififi:1122, 1122, 1122
The Handmaiden:1125, 1125, 1125
The Passion of Joan of Arc:1127, 1127, 1127
The 400 Blows:1133, 1133, 1133
Andrei Rublev:1134, 1134, 1134
Hotel Rwanda:1138, 1138, 1138
Spotlight:1144, 1144, 1144
Amores Perros:1150, 1150, 1150
Rang De Basanti:1151, 1151, 1151
Nausicaä of the Valley of the Wind:1156, 1156, 1156
Rocky:1161, 1161, 1161
La Haine:1163, 1163, 1163
Gangs of Wasseypur:1163, 1163, 1163
Monsters, Inc:1169, 1169, 1169
Rebecca:1169, 1169, 1169
Portrait of a Lady on Fire:1173, 1173, 1173
Before Sunset:1181, 1181, 1181
It Happened One Night:1186, 1186, 1186
The Circus:1194, 1194, 1194
In the Mood for Love:1195, 1195, 1195
Paris, Texas:1198, 1198, 1198
Drishyam:1203, 1203, 1203
The Invisible Guest:1204, 1204, 1204
The Help:1210, 1210, 1210
The Princess Bride:1215, 1215, 1215
The Terminator:1223, 1223, 1223
The Battle of Algiers:1228, 1228, 1228
A Silent Voice: The Movie:1231, 1231, 1231
Swades:1234, 1234, 1234
Lagaan: Once Upon a Time in India:1236, 1236, 1236
Throne of Blood:1239, 1239, 1239

In [7]:
len(streaming)

1239

In [8]:
len(title)

1239

In [9]:
len(price)

1239

In [11]:
google_scrape = pd.DataFrame({'Title': title,
            'Streaming On' : streaming,
            'Price' : price
            })

In [13]:
google_scrape.head(5)

                      Title        Streaming On                 Price
0  The shawshank redemption                Hulu  Premium subscription
1  The shawshank redemption               Starz          Subscription
2  The shawshank redemption            Sling TV  Premium subscription
3  The shawshank redemption  Amazon Prime Video  Premium subscription
4  The shawshank redemption              iTunes            From $3.99

In [14]:
google_scrape.to_csv("../Output/google_scrape.csv", index = False)